image: node:8.10-alpine
pipelines:
  default:
    - step:
        name: Run tests
        trigger: automatic
        caches:
          - node
        script:
          - export ENVIRONMENT=dev
          - apk add --no-cache bash

          - make ci

    - step:
        name: Deploy to dev
        trigger: manual
        deployment: dev
        caches:
          - node
        script:
          - export ENVIRONMENT=dev
          - apk add --no-cache bash

          - make install_production
          - make deploy_serverless

    - step:
        name: Deploy to test
        trigger: manual
        deployment: test
        caches:
          - node
        script:
          - export ENVIRONMENT=test
          - apk add --no-cache bash

          - make install_production
          - make deploy_serverless

    - step:
        name: Deploy to staging
        trigger: manual
        deployment: stage
        caches:
          - node
        script:
          - export ENVIRONMENT=stage
          - apk add --no-cache bash

          - make install_production
          - make deploy_serverless

    - step:
        name: Deploy to Prod
        trigger: manual
        deployment: production
        caches:
          - node
        script:
          - export ENVIRONMENT=prod
          - apk add --no-cache bash

          - make install_production
          - make deploy_serverless

  custom:
    deploy_sns_dev:
      - step:
          script:
            - export ENVIRONMENT=dev
            - apk add --no-cache bash
            - make deploy_sns

    deploy_sqs_dev:
      - step:
          script:
            - export ENVIRONMENT=dev
            - apk add --no-cache bash
            - make deploy_sqs


    deploy_sns_test:
      - step:
          script:
            - export ENVIRONMENT=test
            - apk add --no-cache bash
            - make deploy_sns

    deploy_sqs_test:
      - step:
          script:
            - export ENVIRONMENT=test
            - apk add --no-cache bash
            - make deploy_sqs

    deploy_sns_prod:
      - step:
          script:
            - export ENVIRONMENT=prod
            - apk add --no-cache bash
            - make deploy_sns

    deploy_sqs_prod:
      - step:
          script:
            - export ENVIRONMENT=prod
            - apk add --no-cache bash
            - make deploy_sqs

    deploy_config_dev:
      - step:
          script:
            - export ENVIRONMENT=dev
            - apk add --no-cache bash
            - make validate_config
            - make deploy_config

    deploy_config_test:
      - step:
          script:
            - export ENVIRONMENT=test
            - apk add --no-cache bash
            - make validate_config
            - make deploy_config

    deploy_config_prod:
      - step:
          script:
            - export ENVIRONMENT=prod
            - apk add --no-cache bash
            - make validate_config
            - make deploy_config

