AWSTemplateFormatVersion: 2010-09-09
Description: aws-sns-sqs sns stack. This needs to be deployed first.

Parameters:
  Service:
    Type: String
  Environment:
    Type: String

Resources:

  EventsSNS:
    Description: Configuration will be published there
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub ${Service}
      TopicName: !Sub ${Service}

  ArtifactoryBucket:
    Description: Artifactory bucket
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Service}-artifactory

Outputs:
  EventsSNSTopicArn:
    Description: Event SNS Topic Arn
    Value: !Ref EventsSNS
    Export:
      Name: EventsSNSArn

  EventsSNSTopic:
    Description: Nav Event SNS Topic Name
    Value: !GetAtt EventsSNS.TopicName
    Export:
      Name: EventsSNSTopic

  ArtifactoryBucket:
    Description: Place where artifactory will be created for this project
    Value: !Ref ArtifactoryBucket
    Export:
      Name: !Sub ArtifactoryBucket
